sensors:
  logical_camera_1:
    type: logical_camera
    pose:
      xyz: [-0.716, -0.49, 1.485]
      rpy: [0, 1.338, 'pi']
  logical_camera_2:
    type: logical_camera
    pose:
      xyz: [-0.716, 0.32, 1.485]
      rpy: [0, 1.338, 'pi']
  logical_camera_3:
    type: logical_camera
    pose:
      xyz: [-0.716, 1.13, 1.485]
      rpy: [0, 1.338, 'pi']
  logical_camera_4:
    type: logical_camera
    pose:
      xyz: [-0.716, 1.94, 1.485]
      rpy: [0, 1.338, 'pi']
  logical_camera_5:
    type: logical_camera
    pose:
      xyz: [-0.716, 2.75, 1.485]
      rpy: [0, 1.338, 'pi']
