sensors:
  agv1_logical_cam:
    type: logical_camera
    pose:
      xyz: [0.3, 3.15, 1.3]
      rpy: [0, 'pi/2', 0]
  agv2_logical_cam:
    type: logical_camera
    pose:
      xyz: [0.3, -3.15, 1.3]
      rpy: [0, 'pi/2', 0]

  bin1_logical_cam:
    type: logical_camera
    pose:
      xyz: [-0.3, -1.922, 1.27]
      rpy: [0.0, 1.5707, 0]
  bin2_logical_cam:
    type: logical_camera
    pose:
      xyz: [-0.3,-1.153, 1.27]
      rpy: [0.0, 1.5707, 0]
  bin3_logical_cam:
    type: logical_camera
    pose:
      xyz: [-0.3, -0.378, 1.27]
      rpy: [0.0, 1.5707, 0]

  bin4_logical_cam:
    type: logical_camera
    pose:
      xyz: [-0.3, 0.383, 1.27]
      rpy: [0.0, 1.5707, 0]
  bin5_logical_cam:
    type: logical_camera
    pose:
      xyz: [-0.3, 1.151, 1.27]
      rpy: [0.0, 1.5707, 0]
  bin6_logical_cam:
    type: logical_camera
    pose:
      xyz: [-0.3, 1.931, 1.27]
      rpy: [0.0, 1.5707, 0]

  conveyor1_logical_cam:
    type: logical_camera
    pose:
      xyz: [1.208, 4.5, 1.445]
      rpy: [0.0, 1.5707, 0]

  conveyor2_logical_cam:
    type: logical_camera
    pose:
      xyz: [1.208, -2, 1.445]
      rpy: [0.0, 1.5707, 0]

  laser_profiler_1:
    type: laser_profiler
    pose:
      xyz: [1.21, 4, 1.2]
      rpy: ['-pi', 'pi/2', 'pi/2']

